name: golangci-lint
on:
  pull_request:
  push:
    branches:
      - main*

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    runs-on: charon-ci
    steps:
      # Config options can be found in README here: https://github.com/golangci/golangci-lint-action
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: ./.github/actions/setup-go
      - name: golangci-lint
        uses: golangci/golangci-lint-action@0a35821d5c230e903fcfe077583637dea1b27b47 # v9.0.0
        with:
          version: v2.6.1
