name: pre-commit
on:
  pull_request:
  push:
    branches:
      - main*
jobs:
  pre-commit:
    runs-on: charon-ci
    env:
      SKIP: golangci-lint,run-go-tests,no-commit-to-branch
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0 # Disable shallow checkout
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      - uses: ./.github/actions/setup-go
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
