name: pre-commit
on:
  pull_request:
  push:
    branches:
      - main*
jobs:
  pre-commit:
    runs-on: charon-ci
    env:
      SKIP: golangci-lint,run-go-tests,no-commit-to-branch
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0 # Disable shallow checkout
      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
      - uses: ./.github/actions/setup-go
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc8934aa456 # v3.0.1
