name: track-pr
on:
  pull_request:
    types: [closed]

jobs:
  trackpr:
    runs-on: ubuntu-latest
    env:
      GITHUB_PR: ${{ toJSON(github.event.pull_request) }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v2
        with:
          go-version: '1.19'

      - name: "Track PR"
        run: go run testutil/trackpr/main.go testutil/trackpr/track.go
