name: track-pr
on:
  pull_request:
    types: [closed]

jobs:
  trackpr:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      GITHUB_PR: ${{ toJSON(github.event.pull_request) }}
      GH_TOKEN: ${{ secrets.GH_ORG_ADMIN_SECRET }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20.3'

      - name: "Track PR"
        run: go run github.com/obolnetwork/charon/testutil/trackpr
